# Generated by Django 6.0.3 on 2026-03-22 06:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], db_index=True, default='draft', max_length=10)),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('subscription_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'indexes': [models.Index(fields=['owner', 'status'], name='planner_pro_owner_8bfe01_idx'), models.Index(fields=['subscription_id'], name='planner_pro_subscri_44c273_idx')],
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rotation', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='planner.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'type'], name='planner_ele_project_599b78_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('x2', models.IntegerField()),
                ('y2', models.IntegerField()),
                ('thickness', models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(1)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walls', to='planner.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project'], name='planner_wal_project_8f60be_idx')],
            },
        ),
    ]
