# Generated by Django 6.0.3 on 2026-03-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='planner_pro_owner_8bfe01_idx',
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='planner_pro_owner_bdf1d0_idx'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
