# Generated by Django 6.0.3 on 2026-03-22 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('rotation', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Placed Element',
            },
        ),
        migrations.RemoveIndex(
            model_name='element',
            name='planner_ele_project_599b78_idx',
        ),
        migrations.AddField(
            model_name='projectelement',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='planner.element'),
        ),
        migrations.AddField(
            model_name='projectelement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_elements', to='planner.project'),
        ),
        migrations.RemoveField(
            model_name='element',
            name='project',
        ),
        migrations.RemoveField(
            model_name='element',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='element',
            name='x',
        ),
        migrations.RemoveField(
            model_name='element',
            name='y',
        ),
    ]
